version: '2'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: jmleroux
      MYSQL_PASSWORD: jmleroux
      MYSQL_DATABASE: jmleroux
    ports:
      - '23306:3306'
    networks:
      - jmleroux

  fpm:
    image: jmleroux/fpm:php-7.1
    depends_on:
      - mysql
    environment:
      COMPOSER_HOME: /home/docker/.composer
      PHP_IDE_CONFIG: 'serverName=jmleroux-cli'
      PHP_XDEBUG_ENABLED: 0
      PHP_XDEBUG_IDE_KEY: XDEBUG_IDE_KEY
      PHP_XDEBUG_REMOTE_HOST: xxx.xxx.xxx.xxx
      XDEBUG_CONFIG: 'remote_host=xxx.xxx.xxx.xxx'
    user: docker
    volumes:
      - ./:/srv/jmleroux
      - ~/.composer:/home/docker/.composer
    working_dir: /srv/jmleroux
    networks:
      - jmleroux

  httpd:
    image: httpd:2.4
    depends_on:
      - fpm
    environment:
      PHP_IDE_CONFIG: 'serverName=jmleroux-server'
    ports:
      - '8080:80'
    volumes:
      - ./:/srv/jmleroux:ro
      - ./docker/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/jmleroux.conf:/usr/local/apache2/conf/vhost.conf
    networks:
      - jmleroux

  node:
    image: node:8
    user: node
    volumes:
      - ./:/srv/jmleroux
      - ~/.npm:/home/node/.npm
    working_dir: /srv/jmleroux
    networks:
      - jmleroux

networks:
  jmleroux: ~
